version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-native-web
    versions:
    - 0.15.0
    - 0.15.1
    - 0.15.3
    - 0.15.5
    - 0.15.6
    - 0.15.7
    - 0.16.0
  - dependency-name: "@types/react-native"
    versions:
    - 0.64.0
    - 0.64.1
    - 0.64.2
  - dependency-name: "@types/webpack"
    versions:
    - 5.0.0
  - dependency-name: type-fest
    versions:
    - 0.21.0
    - 0.21.1
    - 0.21.2
    - 0.21.3
    - 1.0.0
    - 1.0.1
  - dependency-name: html-webpack-plugin
    versions:
    - 5.0.0
    - 5.1.0
    - 5.2.0
    - 5.3.0
  - dependency-name: metro-react-native-babel-preset
    versions:
    - 0.65.0
    - 0.65.1
    - 0.65.2
  - dependency-name: react-native-vector-icons
    versions:
    - 8.0.0
